In [1]:
import pandas as pd

In [2]:
#ds = pd.read_csv('Crime_Data_from_2010_to_2019.csv')

In [4]:
df = ds.drop(['Mocodes', 'Part 1-2', 'Crm Cd 1','Crm Cd 2','Crm Cd 3','Crm Cd 4'], axis=1)

In [5]:
df[df['Premis Cd']== 256.0]['Premis Desc'].value_counts(ascending=False)

Series([], Name: count, dtype: int64)

In [6]:
df[df['Premis Cd']== 418.0]

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Crm Cd,Crm Cd Desc,Vict Age,...,Premis Cd,Premis Desc,Weapon Used Cd,Weapon Desc,Status,Status Desc,LOCATION,Cross Street,LAT,LON
1686767,180126492,10/19/2018 12:00:00 AM,10/03/2018 12:00:00 AM,235,1,Central,195,310,BURGLARY,57,...,418.0,NaN,NaN,NaN,IC,Invest Cont,1600 S MAIN ST,NaN,34.0336,-118.2626
1701466,181911543,05/24/2018 12:00:00 AM,05/24/2018 12:00:00 AM,535,19,Mission,1945,320,"BURGLARY, ATTEMPTED",28,...,418.0,NaN,NaN,NaN,IC,Invest Cont,10700 N SEPULVEDA BL,NaN,34.2646,-118.4673
1701948,180300555,02/17/2018 12:00:00 AM,02/17/2018 12:00:00 AM,2225,3,Southwest,335,753,DISCHARGE FIREARMS/SHOTS FIRED,17,...,418.0,NaN,106.0,UNKNOWN FIREARM,AA,Adult Arrest,2400 W JEFFERSON BL,NaN,34.0276,-118.3229
1706049,181208578,03/01/2018 12:00:00 AM,02/27/2018 12:00:00 AM,1700,12,77th Street,1243,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",59,...,418.0,NaN,NaN,NaN,IC,Invest Cont,2000 W FLORENCE AV,NaN,33.9790,-118.3112
1709059,180129081,11/28/2018 12:00:00 AM,11/28/2018 12:00:00 AM,1110,1,Central,195,440,THEFT PLAIN - PETTY ($950 & UNDER),49,...,418.0,NaN,NaN,NaN,IC,Invest Cont,100 W VENICE BL,NaN,34.0336,-118.2626
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2110368,190906676,02/23/2019 12:00:00 AM,02/23/2019 12:00:00 AM,945,9,Van Nuys,943,946,OTHER MISCELLANEOUS CRIME,0,...,418.0,NaN,NaN,NaN,IC,Invest Cont,14300 OXNARD ST,NaN,34.1794,-118.4444
2110416,190707087,03/04/2019 12:00:00 AM,01/24/2019 12:00:00 AM,300,7,Wilshire,721,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",35,...,418.0,NaN,NaN,NaN,IC,Invest Cont,100 S ROBERTSON BL,NaN,34.0753,-118.3837
2116887,191227224,11/19/2019 12:00:00 AM,11/19/2019 12:00:00 AM,2240,12,77th Street,1255,210,ROBBERY,0,...,418.0,NaN,102.0,HAND GUN,IC,Invest Cont,1200 W FLORENCE AV,NaN,33.9746,-118.2962
2116926,190223459,12/17/2019 12:00:00 AM,12/15/2019 12:00:00 AM,2145,2,Rampart,236,668,"EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)",0,...,418.0,NaN,NaN,NaN,IC,Invest Cont,100 S ALVARADO ST,NaN,34.0667,-118.2703
2122407,190616877,08/07/2019 12:00:00 AM,08/07/2019 12:00:00 AM,314,6,Hollywood,649,310,BURGLARY,0,...,418.0,NaN,NaN,NaN,IC,Invest Cont,5200 HOLLYWOOD BL,NaN,34.1018,-118.3034